spring.application.name=digital_mediator
server.port=6665
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=${DRIVER_CLASS_NAME}


minio.url= ${MINIO_URL}
minio.access.key= ${MINIO_ACCESS_KEY}
minio.secret.key= ${MINIO_SECRET_KEY}
minio.bucket.name=${MINIO_BUCKET_NAME}


spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.listener.simple.acknowledge-mode=auto
spring.rabbitmq.listener.simple.prefetch=1


ai.model.url=${AI_MODEL_URL}
index.control.port=${INDEX_CONTROL_PORT}

spring.servlet.multipart.enabled= true
spring.servlet.multipart.max-file-size= 10MB
spring.servlet.multipart.max-request-size= 50MB