spring.application.name=digital_mediator
server.port=${PORT}
server.address=0.0.0.0
spring.config.import=optional:file:.env[.properties]

minio.url= ${MINIO_URL}
minio.access.key= ${MINIO_ACCESS_KEY}
minio.secret.key= ${MINIO_SECRET_KEY}
minio.bucket.name=${MINIO_BUCKET_NAME}


spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.listener.simple.acknowledge-mode=auto
spring.rabbitmq.listener.simple.prefetch=1

spring.rabbitmq.document.queue=${RABBITMQ_DOCUMENT_QUEUE}
spring.rabbitmq.document.exchange=${RABBITMQ_DOCUMENT_EXCHANGE}
spring.rabbitmq.document.routing-key=${RABBITMQ_DOCUMENT_ROUTING_KEY}

spring.rabbitmq.dlq.queue=${RABBITMQ_DLQ_QUEUE}
spring.rabbitmq.dlq.exchange=${RABBITMQ_DLQ_EXCHANGE}
spring.rabbitmq.dlq.routing-key=${RABBITMQ_DLQ_ROUTING_KEY}

spring.rabbitmq.result.queue=${RABBITMQ_RESULT_QUEUE}
spring.rabbitmq.result.exchange=${RABBITMQ_RESULT_EXCHANGE}
spring.rabbitmq.result.pending.routing-key=${RABBITMQ_RESULT_PENDING_ROUTING_KEY}
spring.rabbitmq.result.processing.routing-key=${RABBITMQ_RESULT_PROCESSING_ROUTING_KEY}
spring.rabbitmq.result.success.routing-key=${RABBITMQ_RESULT_SUCCESS_ROUTING_KEY}
spring.rabbitmq.result.failure.routing-key=${RABBITMQ_RESULT_FAILURE_ROUTING_KEY}

ai.model.url=${AI_MODEL_URL}
index.control.port=${INDEX_CONTROL_PORT}

spring.servlet.multipart.enabled= true
spring.servlet.multipart.max-file-size= 10MB
spring.servlet.multipart.max-request-size= 50MB